Support clipboard copy on macOS
hobarrera/totp-cli pull request #3
Opened 2017-02-25 22:28 UTC by comutt

macOS has `pbcopy` for clipboard copying,
so I've added condition to switch command to copy to clipboard.

2017-02-25 23:32 UTC, WhyNotHugo requested changes
Hi! Thanks for your interest and contribution. There a couple of tweaks I'd make, but this looks great overall!

2017-02-25 23:32 UTC, hobarrera commented on totp/__init__.py
> +        else:
I think that `xclip` should be used as the fallback, since it'll work on just about any OS that runs X (I think only windows doesn't).

2017-02-25 23:32 UTC, hobarrera commented on totp/__init__.py
> +        print('{} not found. Not copying code'.format(command[0]), file=sys.stderr)
This should probably be `command[0]`, since otherwise we also print all the flags.

2017-02-26 06:06 UTC, comutt commented on totp/__init__.py
> +        else:
@hobarrera 
Changed to use `pbcopy` on Darwin, `clip` on Windows, `xclip` on any other platforms.

2017-02-26 06:07 UTC, comutt commented on totp/__init__.py
> +        print('{} not found. Not copying code'.format(command[0]), file=sys.stderr)
@hobarrera 
> This should probably be command[0].
Is `.format(command[0])` not good, is it?

2017-02-26 12:23 UTC, hobarrera commented on totp/__init__.py
> +        print('{} not found. Not copying code'.format(command[0]), file=sys.stderr)
I didn't understand this question (maybe I was too asleep when I replied yesterday 😅 ).

2017-02-26 12:23 UTC, WhyNotHugo approved these changes

2017-02-26 12:23 UTC, merged

2017-02-26 12:34 UTC, hobarrera commented
Oops, this kinda slipped by me: we should also update the docs, to reflect optional requirements.

I was about to do this and was wondering: is `pbcopy` preinstalled on macOS, or does it have to be installed separately?

2017-02-26 13:43 UTC, comutt commented
pbcopy is shipped by default with macOS. no additional installation
required.